/*
 * SPDX-FileCopyrightText: silkvo social-engine contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 */

export const packedMeetParticipantSchema = {
	type: 'object',
	properties: {
		id: { type: 'string', optional: false, nullable: false, format: 'id' },
		meetId: { type: 'string', optional: false, nullable: false, format: 'id' },
		userId: { type: 'string', optional: false, nullable: true, format: 'id' },
		user: { type: 'object', optional: true, nullable: true, ref: 'UserLite' },
		kind: { type: 'string', optional: false, nullable: false, enum: ['user', 'reserved', 'plusOne'] },
		sponsorId: { type: 'string', optional: false, nullable: true, format: 'id' },
		displayName: { type: 'string', optional: false, nullable: true },
		declaredLevel: { type: 'number', optional: false, nullable: true },
		status: { type: 'string', optional: false, nullable: false, enum: ['requested', 'invited', 'confirmed', 'waitlisted', 'hold', 'maybe', 'declined', 'removed', 'left'] },
		waitlistRank: { type: 'number', optional: false, nullable: true },
		holdExpiresAt: { type: 'string', optional: false, nullable: true, format: 'date-time' },
		isHost: { type: 'boolean', optional: false, nullable: false },
		isCoach: { type: 'boolean', optional: false, nullable: false },
		isReferee: { type: 'boolean', optional: false, nullable: false },
		isPaymentCollector: { type: 'boolean', optional: false, nullable: false },
		tags: { type: 'array', optional: false, nullable: false, items: { type: 'string', optional: false, nullable: false } },
		teamKey: { type: 'string', optional: false, nullable: true },
		courtIndex: { type: 'number', optional: false, nullable: true },
		level: { type: 'number', optional: false, nullable: true },
		statusChangedAt: { type: 'string', optional: false, nullable: true, format: 'date-time' },
		checkedInAt: { type: 'string', optional: false, nullable: true, format: 'date-time' },
	},
} as const;

export const packedMeetSchema = {
	type: 'object',
	properties: {
		id: { type: 'string', optional: false, nullable: false, format: 'id' },
		createdAt: { type: 'string', optional: false, nullable: false, format: 'date-time' },
		referenceCode: { type: 'string', optional: false, nullable: false },
		hostId: { type: 'string', optional: false, nullable: false, format: 'id' },
		host: { type: 'object', optional: true, nullable: true, ref: 'UserLite' },
		channelId: { type: 'string', optional: false, nullable: true, format: 'id' },
		channel: { type: 'object', optional: true, nullable: true, ref: 'Channel' },
		chatRoomId: { type: 'string', optional: false, nullable: true, format: 'id' },
		type: { type: 'string', optional: false, nullable: false, enum: ['listing', 'managed'] },
		sport: { type: 'string', optional: false, nullable: false },
		format: { type: 'string', optional: false, nullable: true },
		name: { type: 'string', optional: false, nullable: false },
		notes: { type: 'string', optional: false, nullable: true },
		startAt: { type: 'string', optional: false, nullable: false, format: 'date-time' },
		endAt: { type: 'string', optional: false, nullable: false, format: 'date-time' },
		durationMinutes: { type: 'number', optional: false, nullable: false },
		timezone: { type: 'string', optional: false, nullable: false },
		venueName: { type: 'string', optional: false, nullable: true },
		venueAddress: { type: 'string', optional: false, nullable: true },
		lat: { type: 'number', optional: false, nullable: true },
		lng: { type: 'number', optional: false, nullable: true },
		venueRef: { type: 'string', optional: false, nullable: true },
		distanceKm: { type: 'number', optional: true, nullable: true },
		capacity: { type: 'number', optional: false, nullable: false },
		hostPlays: { type: 'boolean', optional: false, nullable: false },
		visibility: { type: 'string', optional: false, nullable: false, enum: ['public', 'private', 'club'] },
		status: { type: 'string', optional: false, nullable: false, enum: ['active', 'cancelled'] },
		isPast: { type: 'boolean', optional: false, nullable: false },
		autoApprove: { type: 'boolean', optional: false, nullable: false },
		allowPlusOne: { type: 'boolean', optional: false, nullable: false },
		guestsPerMember: { type: 'number', optional: false, nullable: false },
		feeType: { type: 'string', optional: false, nullable: false, enum: ['none', 'free', 'perPax', 'autoSplit'] },
		feeAmount: { type: 'number', optional: false, nullable: true },
		feeCurrency: { type: 'string', optional: false, nullable: false },
		paymentInfo: { type: 'string', optional: false, nullable: true },
		payByMinutes: { type: 'number', optional: false, nullable: true },
		cancellationFreezeHours: { type: 'number', optional: false, nullable: false },
		gateType: { type: 'string', optional: false, nullable: false, enum: ['guidance', 'autoApprove', 'strict'] },
		levelBasis: { type: 'string', optional: false, nullable: false, enum: ['self', 'duprSingles', 'duprDoubles'] },
		minLevel: { type: 'number', optional: false, nullable: true },
		maxLevel: { type: 'number', optional: false, nullable: true },
		gender: { type: 'string', optional: false, nullable: false, enum: ['any', 'coed', 'female', 'male'] },
		ageGroup: { type: 'string', optional: false, nullable: false, enum: ['any', 'junior', 'adult', 'senior'] },
		submitMatches: { type: 'boolean', optional: false, nullable: false },
		seriesId: { type: 'string', optional: false, nullable: true },
		confirmedCount: { type: 'number', optional: false, nullable: false },
		waitlistedCount: { type: 'number', optional: false, nullable: false },
		requestedCount: { type: 'number', optional: false, nullable: false },
		spotsLeft: { type: 'number', optional: false, nullable: false },
		myStatus: { type: 'string', optional: false, nullable: true, enum: ['requested', 'invited', 'confirmed', 'waitlisted', 'hold', 'maybe', 'declined', 'removed', 'left', null] },
		myGate: { type: 'string', optional: false, nullable: true, enum: ['approved', 'requestOnly', 'denied', null] },
		isHost: { type: 'boolean', optional: false, nullable: false },
		participants: { type: 'array', optional: true, nullable: false, items: { type: 'object', optional: false, nullable: false, ref: 'MeetParticipant' } },
	},
} as const;
