/*
 * SPDX-FileCopyrightText: silkvo social-engine contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 */

export const packedMeetParticipantSchema = {
	type: 'object',
	properties: {
		id: { type: 'string', optional: false, nullable: false, format: 'id' },
		meetId: { type: 'string', optional: false, nullable: false, format: 'id' },
		userId: { type: 'string', optional: false, nullable: true, format: 'id' },
		user: { type: 'object', optional: true, nullable: true, ref: 'UserLite' },
		kind: { type: 'string', optional: false, nullable: false, enum: ['user', 'reserved', 'plusOne'] },
		sponsorId: { type: 'string', optional: false, nullable: true, format: 'id' },
		displayName: { type: 'string', optional: false, nullable: true },
		declaredLevel: { type: 'number', optional: false, nullable: true },
		status: { type: 'string', optional: false, nullable: false, enum: ['requested', 'invited', 'confirmed', 'waitlisted', 'hold', 'maybe', 'declined', 'spectator'] },
		waitlistRank: { type: 'number', optional: false, nullable: true },
		extGender: { type: 'string', optional: false, nullable: true },
		extAge: { type: 'string', optional: false, nullable: true },
		positionId: { type: 'string', optional: false, nullable: true },
		paymentType: { type: 'string', optional: false, nullable: true },
		isHost: { type: 'boolean', optional: false, nullable: false },
		isCoach: { type: 'boolean', optional: false, nullable: false },
		isReferee: { type: 'boolean', optional: false, nullable: false },
		isPaymentCollector: { type: 'boolean', optional: false, nullable: false },
		tags: { type: 'array', optional: false, nullable: false, items: { type: 'string', optional: false, nullable: false } },
		teamKey: { type: 'string', optional: false, nullable: true },
		courtIndex: { type: 'number', optional: false, nullable: true },
		level: { type: 'number', optional: false, nullable: true },
		statusChangedAt: { type: 'string', optional: false, nullable: true, format: 'date-time' },
		checkedInAt: { type: 'string', optional: false, nullable: true, format: 'date-time' },
	},
} as const;

export const packedMeetSchema = {
	type: 'object',
	properties: {
		id: { type: 'string', optional: false, nullable: false, format: 'id' },
		createdAt: { type: 'string', optional: false, nullable: false, format: 'date-time' },
		referenceCode: { type: 'string', optional: false, nullable: false },
		hostId: { type: 'string', optional: false, nullable: false, format: 'id' },
		host: { type: 'object', optional: true, nullable: true, ref: 'UserLite' },
		channelId: { type: 'string', optional: false, nullable: true, format: 'id' },
		channel: { type: 'object', optional: true, nullable: true, ref: 'Channel' },
		chatRoomId: { type: 'string', optional: false, nullable: true, format: 'id' },
		safety: { type: 'object', optional: true, nullable: true, description: 'SAFETY-V1: newHostUserIds + blockedUserIds for the viewer (Reclub Safety First interstitial)' },
		type: { type: 'string', optional: false, nullable: false, enum: ['listing', 'managed'] },
		sport: { type: 'string', optional: false, nullable: false },
		format: { type: 'string', optional: false, nullable: true },
		name: { type: 'string', optional: false, nullable: false },
		notes: { type: 'string', optional: false, nullable: true },
		startAt: { type: 'string', optional: false, nullable: false, format: 'date-time' },
		endAt: { type: 'string', optional: false, nullable: false, format: 'date-time' },
		durationMinutes: { type: 'number', optional: false, nullable: false },
		timezone: { type: 'string', optional: false, nullable: false },
		venueName: { type: 'string', optional: false, nullable: true },
		venueAddress: { type: 'string', optional: false, nullable: true },
		lat: { type: 'number', optional: false, nullable: true },
		lng: { type: 'number', optional: false, nullable: true },
		venueRef: { type: 'string', optional: false, nullable: true },
		distanceKm: { type: 'number', optional: true, nullable: true },
		capacity: { type: 'number', optional: false, nullable: false },
		hostPlays: { type: 'boolean', optional: false, nullable: false },
		visibility: { type: 'string', optional: false, nullable: false, enum: ['public', 'private'] },
		status: { type: 'string', optional: false, nullable: false, enum: ['pending', 'active', 'cancelled'] },
		isPast: { type: 'boolean', optional: false, nullable: false },
		autoApprove: { type: 'boolean', optional: false, nullable: false },
		allowPlusOne: { type: 'boolean', optional: false, nullable: false },
		feeType: { type: 'string', optional: false, nullable: false, enum: ['none', 'free', 'perPax', 'autoSplit'] },
		feeAmount: { type: 'number', optional: false, nullable: true },
		feeCurrency: { type: 'string', optional: false, nullable: false },
		paymentInfo: { type: 'string', optional: false, nullable: true },
		confirmed: { type: 'number', optional: false, nullable: false },
		duprAccountGate: { type: 'string', optional: false, nullable: false },
		repeatInterval: { type: 'string', optional: false, nullable: true },
		repeatCount: { type: 'number', optional: false, nullable: true },
		blindTeamsMinutes: { type: 'number', optional: false, nullable: true },
		allowPlayerScoring: { type: 'boolean', optional: false, nullable: false },
		sendNotifications: { type: 'boolean', optional: false, nullable: false },
		rosterVisibility: { type: 'array', optional: false, nullable: false, items: { type: 'string' } },
		flags: { type: 'array', optional: false, nullable: false, items: { type: 'string' } },
		venueId: { type: 'string', optional: false, nullable: true },
		cancellationFreezeHours: { type: 'number', optional: false, nullable: false },
		gateType: { type: 'string', optional: false, nullable: false, enum: ['guidance', 'autoApprove', 'strict'] },
		levelBasis: { type: 'string', optional: false, nullable: false, enum: ['self', 'duprSingles', 'duprDoubles'] },
		minLevel: { type: 'number', optional: false, nullable: true },
		maxLevel: { type: 'number', optional: false, nullable: true },
		gender: { type: 'string', optional: false, nullable: false, enum: ['any', 'coed', 'female', 'male'] },
		ageGroup: { type: 'string', optional: false, nullable: false, enum: ['any', 'junior', 'adult', 'senior'] },
		submitMatches: { type: 'boolean', optional: false, nullable: false },
		seriesId: { type: 'string', optional: false, nullable: true },
		confirmedCount: { type: 'number', optional: false, nullable: false },
		waitlistedCount: { type: 'number', optional: false, nullable: false },
		requestedCount: { type: 'number', optional: false, nullable: false },
		spotsLeft: { type: 'number', optional: false, nullable: false },
		myStatus: { type: 'string', optional: false, nullable: true, enum: ['requested', 'invited', 'confirmed', 'waitlisted', 'hold', 'maybe', 'declined', 'spectator'] },
		myGate: { type: 'string', optional: false, nullable: true, enum: ['approved', 'requestOnly', 'denied'] },
		isHost: { type: 'boolean', optional: false, nullable: false },
		participants: { type: 'array', optional: true, nullable: false, items: { type: 'object', optional: false, nullable: false, ref: 'MeetParticipant' } },
	},
} as const;

/** MEET-MATCH-V1: one row of Reclub's Matches pane. isPending = no scores; winnerTeam from score sets (majority of games). */
/** SAFETY-V1: what a viewer may see about a person (reviews visible to them + no-show count). */
export const packedPlayerReviewsSchema = {
	type: 'object',
	properties: {
		userId: { type: 'string', optional: false, nullable: false, format: 'id' },
		endorsements: { type: 'array', optional: false, nullable: false, items: { type: 'object', properties: {
			author: { type: 'object', optional: false, nullable: true, ref: 'UserLite' }, body: { type: 'string', optional: false, nullable: true }, createdAt: { type: 'string', optional: false, nullable: false, format: 'date-time' } } } },
		feedback: { type: 'array', optional: false, nullable: false, items: { type: 'object', properties: {
			author: { type: 'object', optional: false, nullable: true, ref: 'UserLite' }, body: { type: 'string', optional: false, nullable: true }, createdAt: { type: 'string', optional: false, nullable: false, format: 'date-time' } } } },
		warnings: { type: 'array', optional: false, nullable: false, items: { type: 'object', properties: {
			author: { type: 'object', optional: false, nullable: true, ref: 'UserLite' }, body: { type: 'string', optional: false, nullable: true }, createdAt: { type: 'string', optional: false, nullable: false, format: 'date-time' } } } },
		warningCount: { type: 'number', optional: false, nullable: false },
		warningsPublic: { type: 'boolean', optional: false, nullable: false },
		noShows30d: { type: 'number', optional: false, nullable: false },
		kudos: { type: 'object', optional: false, nullable: false, description: 'endorsement body → count (Reclub kudo dimensions live in the body)' },
		mine: { type: 'object', optional: false, nullable: false, description: 'the viewer\'s own rows about this person, by type' },
	},
} as const;

export const packedMeetMatchSchema = {
	type: 'object',
	properties: {
		id: { type: 'string', optional: false, nullable: false, format: 'id' },
		meetId: { type: 'string', optional: false, nullable: false, format: 'id' },
		round: { type: 'number', optional: false, nullable: true },
		courtIndex: { type: 'number', optional: false, nullable: true },
		team1Ids: { type: 'array', optional: false, nullable: false, items: { type: 'string', format: 'id' } },
		team2Ids: { type: 'array', optional: false, nullable: false, items: { type: 'string', format: 'id' } },
		scores: { type: 'array', optional: false, nullable: false, items: { type: 'array', items: { type: 'number' } } },
		isPending: { type: 'boolean', optional: false, nullable: false },
		winnerTeam: { type: 'number', optional: false, nullable: true },
		canUpdateScore: { type: 'boolean', optional: false, nullable: false },
		canManage: { type: 'boolean', optional: false, nullable: false },
		duprStatus: { type: 'string', optional: false, nullable: true, enum: ['queued', 'submitted', 'failed', 'ineligible'] },
		duprSubmittedBy: { type: 'object', optional: false, nullable: true, ref: 'UserLite' },
		duprSubmittedAt: { type: 'string', optional: false, nullable: true, format: 'date-time' },
		duprRef: { type: 'string', optional: false, nullable: true },
		duprError: { type: 'string', optional: false, nullable: true },
		duprEligibility: { type: 'object', optional: true, nullable: true },
		updatedAt: { type: 'string', optional: false, nullable: false, format: 'date-time' },
	},
} as const;
