'use strict';
// venues-discover-rest: remove every fixture of lane venues-discover-rest on UAT (se_sbx). Each step is independent.
process.env.BASE = 'https://uat.social.silkvo.com';
const fs = require('fs');
const { execFileSync } = require('child_process');
const ENG = 'https://uat.social.silkvo.com';
const TAG = '[probe] venues-discover-rest';
const sql = (q) => execFileSync('docker', ['exec', '-i', 'social-engine-db-1', 'psql', '-U', 'social', '-d', 'se_sbx', '-Atc', q], { encoding: 'utf8' }).trim();
const lit = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function api(ep, body, token) { const r = await fetch(ENG + '/api/' + ep, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...(body || {}), ...(token ? { i: token } : {}) }) }); const t = await r.text(); let j; try { j = JSON.parse(t); } catch (e) { j = t.slice(0, 120); } return { status: r.status, j }; }
async function retry(fn) { let e; for (let k = 0; k < 5; k++) { try { return await fn(); } catch (x) { e = x; await sleep(4000); } } throw e; }
const QA_P = (fs.readFileSync('/root/hkpl-server/.env', 'utf8').match(/^QA_BYPASS_PASSWORD=(.+)$/m) || [])[1] || 'hkpl-uat-2026';
const { getNativeToken } = require('/root/social-engine/probes/_native-session.cjs');
async function persona(email) { if (email === 'uat+clubowner-mei@hkpl-test.silkvo.com') { const c = await getNativeToken('clubowner-mei'); const me = await api('i', {}, c.token); return { token: c.token, id: c.userId, me: me.j }; } return retry(async () => { const r = await fetch(ENG + '/api/v1/auth/qa/by-email/' + encodeURIComponent(email) + '?p=' + encodeURIComponent(QA_P), { redirect: 'manual' }); const raw = (r.headers.getSetCookie ? r.headers.getSetCookie() : []).map((c) => c.split(';')[0]); const mj = await (await fetch(ENG + '/api/v1/auth/sso/social', { headers: { cookie: raw.join('; ') } })).json(); const s = await (await fetch(ENG + '/api/adapter/sso', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ jwt: mj.jwt }) })).json(); const me = await api('i', {}, s.token); return { token: s.token, id: me.j.id, me: me.j }; }); }
async function tester(i) { { const c = await getNativeToken(i === 0 ? 'admin' : 'host-ken'); return { token: c.token, id: c.userId }; } return retry(async () => { const { name, value } = await require('/root/social-engine/probes/_session.cjs').getSession(i); const mj = await (await fetch(ENG + '/api/v1/auth/sso/social', { headers: { cookie: name + '=' + value } })).json(); const s = await (await fetch(ENG + '/api/adapter/sso', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ jwt: mj.jwt }) })).json(); const me = await api('i', {}, s.token); return { token: s.token, id: me.j.id }; }); }

module.exports = async function cleanup(opts = {}) {
  const log = [];
  const step = async (name, fn) => { try { const r = await fn(); log.push(name + ': ' + (r == null ? 'ok' : r)); } catch (e) { log.push(name + ': ERROR ' + String(e.message).slice(0, 120)); } };
  let t1, t2;
  await step('tokens', async () => { t1 = await tester(0); t2 = await tester(1); });
  await step('venues', async () => { const ids = sql(`SELECT id FROM venue WHERE name LIKE ${lit(TAG + '%')}`).split('\n').filter(Boolean); if (!ids.length) return 0; sql(`UPDATE meet SET "venueId"=NULL WHERE "venueId" IN (${ids.map(lit).join(',')})`); sql(`DELETE FROM venue WHERE id IN (${ids.map(lit).join(',')})`); return ids.length; });
  await step('clubs', async () => { const ids = sql(`SELECT id FROM channel WHERE name LIKE ${lit(TAG + '%')}`).split('\n').filter(Boolean); if (!ids.length) return 0; const L = ids.map(lit).join(','); sql(`DELETE FROM club_join_request WHERE "channelId" IN (${L})`); sql(`DELETE FROM channel_following WHERE "followeeId" IN (${L})`); sql(`DELETE FROM club_invitation WHERE "channelId" IN (${L})`); sql(`UPDATE channel SET "isArchived"=true, name=${lit(TAG + ' archived')} WHERE id IN (${L})`); return ids.length; });
  await step('notes', async () => { const rows = sql(`SELECT id FROM note WHERE text LIKE ${lit(TAG + '%')}`).split('\n').filter(Boolean); for (const id of rows) { const d = await api('notes/delete', { noteId: id }, t1.token); if (d.status !== 204 && d.status !== 200) sql(`DELETE FROM note WHERE id=${lit(id)}`); } return rows.length; });
  await step('announcements', async () => sql(`DELETE FROM announcement WHERE title LIKE ${lit(TAG + '%')} RETURNING id`).split('\n').filter(Boolean).length);
  await step('places', async () => sql(`DELETE FROM user_location WHERE label LIKE ${lit(TAG + '%')} RETURNING id`).split('\n').filter(Boolean).length);
  await step('t2 onboarding places', async () => { const ids = opts.t2Places || []; if (ids.length) sql(`DELETE FROM user_location WHERE id IN (${ids.map(lit).join(',')})`); return ids.length; });
  await step('live meets', async () => { const ids = sql(`SELECT id FROM meet WHERE name LIKE ${lit(TAG + '%')} AND status <> 'cancelled'`).split('\n').filter(Boolean); for (const id of ids) { const c = await api('meets/cancel', { meetId: id }, t2.token); if (c.status !== 200 && c.status !== 204) sql(`UPDATE meet SET status='cancelled' WHERE id=${lit(id)}`); } return ids.length; });
  await step('mei coaching photos field', async () => { const m = await persona('uat+clubowner-mei@hkpl-test.silkvo.com'); const f = (m.me.fields || []); const keep = opts.meiFields || f.filter((x) => x.name !== 'Coaching photos'); if (keep.length === f.length && !opts.meiFields) return 'nothing'; const r = await api('i/update', { fields: keep }, m.token); return 'restored ' + r.status + ' (' + keep.length + ' fields)'; });
  await step('drive files', async () => { let n = 0; const owners = [[t1, 't1'], [t2, 't2']]; try { const m = await persona('uat+clubowner-mei@hkpl-test.silkvo.com'); owners.push([m, 'mei']); } catch (e) { /* */ } for (const [who] of owners) { const ids = sql(`SELECT id FROM drive_file WHERE "userId"=${lit(who.id)} AND name LIKE 'probe-%'`).split('\n').filter(Boolean); for (const id of ids) { await api('drive/files/delete', { fileId: id }, who.token); n++; } } return n; });
  const left = { venues: sql(`SELECT count(*) FROM venue WHERE name LIKE ${lit(TAG + '%')}`), media: sql(`SELECT count(*) FROM venue_media m LEFT JOIN venue v ON v.id=m."venueId" WHERE v.id IS NULL`), places: sql(`SELECT count(*) FROM user_location WHERE label LIKE ${lit(TAG + '%')}`), announcements: sql(`SELECT count(*) FROM announcement WHERE title LIKE ${lit(TAG + '%')}`), liveClubs: sql(`SELECT count(*) FROM channel WHERE name LIKE ${lit(TAG + '%')} AND "isArchived"=false`), liveMeets: sql(`SELECT count(*) FROM meet WHERE name LIKE ${lit(TAG + '%')} AND status <> 'cancelled'`), driveFiles: sql(`SELECT count(*) FROM drive_file WHERE name LIKE 'probe-vdr%' OR name LIKE 'probe-photo%'`), notes: sql(`SELECT count(*) FROM note WHERE text LIKE ${lit(TAG + '%')}`), coachPhotosFields: sql(`SELECT count(*) FROM user_profile WHERE fields::text LIKE '%Coaching photos%'`) };
  return { log, left };
};
if (require.main === module) module.exports().then((r) => console.log(JSON.stringify(r, null, 1)));
